spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seconddeal?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
server:
  port: 8080




